language: python
python:
- 3.5
install:
- pip install -r requirements.txt
script: nosetests
after_success:
- "./auto.sh"
env:
  global:
    secure: kYVdEonfrQjGXXGvSchqwW6WvrTApPkwWE/lo7Zy2QHBGDVaFeWspqGWNMcPOx/lsQvs4BdXrLPtS/VzJ1jhO5BrhHN7szmgEKKOJ36BLnWJDWlbcMSNKapPXCc1GcYVWdDSvXd4/rCLuc8gmyVM4x2oY8adaiUCvUNKR0CQ23DeyW3B5q/IcFgHy4ar5dRkj8nkVSZX3GsXd4LnX7Mx1ntG1ZCPYbfvN97mOZAwFQ8BP9hV6j3i79lsHaVOmoioenqWFIMtBaEDQH4wwdWIoMAKfCvIAlJNwOLNYjU5X10zxNVVxchgb3BqVJ+j3gRp9mHina2elyKllY1b92DqKAzG6xQLCljRswdLVDOeLzp7ViSBYgqbqVvCRCuP45N24Xl0emm0N78rMY9BWcN4Co0FRWhBfCbcDkxvdoY5cnUgP/aP0fMQdPsq1woWmZzLDvPCmPXq5hEpOjhUxb5cBuGjw2NJZR8GxPTT6NHnX6xFKICC2O87tNPQNEsXTNljTnTDov5c6T2OhQagUi/Aqlwc5KJ1bETaRpP5/rq8RB6fmjyc5ds83jnYK6SLNH1RaTUUnWeszpftACfKPTliv4cIjzCTpslVHAUXfkAPmV6FMgpzvH1Q7ZjnLUJYSZl5jUUmw9hbi1GNu+PaaWUo40+Q4agP3PXTt3B4mf0OhYI=
